title: Cocoa Conferences
description: List of all-English conferences for Cocoa (macOS, iOS, watchOS & tvOS) developers
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
